; Paste your token in front of the equal symbol WITHOUT adding "" or anything
; If you are using multi tokens, Do not put a token in front of the equal symbol. Leave "TOKEN" empty and paste your tokens inside `tokens.txt` separating them by a new line.
[sys]
TOKEN = 
WEBHOOK_URL = https://discord.com/api/webhooks/1490074917327208590/MBfzDrFn5S6vTYDzafinRuDXYJ1-Bj-N7wcGcmLB-DiNTDMD8OB__oFV6LOagiuupal2
MULTI_TOKEN = true
PROXY_MODE = false ;(do not use proxie mode) dropped feature doesnt work anymore (do not use proxie mode)
PROXY_FILE = proxies.txt

; Config for option 1 (Generating usernames) and what to include(true/false).
[config]
digits = true
punctuation = true
string = true
default_delay = 4

; (Seconds) The default delay if not chosen during the process (Longer delay = less chance of getting suspended).
